/**
 * Model and prompt versioning constants.
 *
 * Kept in their own module so both server-only code and pure, testable code
 * can import them without pulling in the SDK or the `server-only` guard.
 */

/**
 * The model used for diagnosis, as an OpenRouter model id (`vendor/model`).
 *
 * Overridable without a code change so the model can be swapped by editing
 * .env.local — the routing layer is the whole point of using OpenRouter.
 * Whatever you pick must support `response_format: json_schema`; see the
 * `requireParameters` note in client.ts for what happens if it doesn't.
 */
export const REPORT_MODEL = process.env.OPENROUTER_MODEL ?? "openai/gpt-5";

/**
 * Bump on ANY change to prompt text, schema, or profile shape. Persisted on
 * every row in `reports` — without it, findings generated by different prompts
 * are indistinguishable after the fact.
 */
export const PROMPT_VERSION = "2026-08-09.2";

/** Minimum tests in the window before a diagnosis is honest rather than noise. */
export const MIN_TESTS_FOR_REPORT = 10;

/** Guard against sending a bloated payload — see PHASE-4.md. */
export const MAX_PROFILE_BYTES = 2048;
