/**
 * Model and prompt versioning constants.
 *
 * Kept in their own module so both server-only code and pure, testable code
 * can import them without pulling in the SDK or the `server-only` guard.
 */

/**
 * The model used for diagnosis, as a Gemini model id.
 *
 * Overridable via GEMINI_MODEL so the model can be swapped by editing
 * .env.local rather than by a code change. Whatever you pick must support
 * structured output (`responseJsonSchema`) — see client.ts.
 */
export const REPORT_MODEL = process.env.GEMINI_MODEL ?? "gemini-3.6-flash";

/**
 * The model used for drill sentences (src/lib/drills/llm.ts).
 *
 * Separate from REPORT_MODEL because the two calls are not alike: this one
 * returns free prose, is a secondary mechanism behind deterministic synthesis,
 * and has nothing persisted or audited — so a preview model is a reasonable
 * trade here in a way it is not for the diagnosis path, whose output is
 * schema-constrained, guarded against fabricated figures, and kept for audit.
 */
export const DRILL_MODEL = process.env.GEMINI_DRILL_MODEL ?? "gemini-3-flash-preview";

/**
 * Bump on ANY change to prompt text, schema, or profile shape. Persisted on
 * every row in `reports` — without it, findings generated by different prompts
 * are indistinguishable after the fact.
 */
export const PROMPT_VERSION = "2026-08-09.2";

/** Minimum tests in the window before a diagnosis is honest rather than noise. */
export const MIN_TESTS_FOR_REPORT = 10;

/** Guard against sending a bloated payload — see PHASE-4.md. */
export const MAX_PROFILE_BYTES = 2048;
